theme:
  name: material
  custom_dir: "./overrides"
  icon:
    logo: logo
  font: false
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/bitwarden
copyright: "&copy; 2022 Bitwarden, Inc."
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: '#'
plugins:
  - search
  - macros
