on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: actions/setup-python@21c0493ecfd34b1217f0a90ec19a327f3cc0a048 # v3.1.2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build Docs
        run: mkdocs build --site-dir ./dist
        working-directory: ./
      - name: Publish
        uses: cloudflare/pages-action@752c4fc911d149221a4173136118c3cc250e9409 # v1.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: developer-docs
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
